version: '3.9'

services:
  core:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - 8000:8000
    volumes:
      - ./core:/core
      - ./static:/static
    command:  python manage.py runserver 0.0.0.0:8000
    environment:
      - DEBUG=1
