# Generated by Django 4.0.4 on 2022-05-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_chase', '0002_rename_name_productgroup_group_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='group_code',
            field=models.CharField(default=0, max_length=250),
        ),
    ]
