# Generated by Django 4.0.4 on 2022-05-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_chase', '0003_productgroup_group_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgroup',
            name='group_code',
            field=models.CharField(max_length=250),
        ),
    ]
