# Generated by Django 4.0.3 on 2022-05-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_chase', '0004_alter_productgroup_group_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='productgroup',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
